dist: xenial
language: python
python:
  - 2.7
  - 3.6
env:
  - KERAS_BACKEND=tensorflow
  - KERAS_BACKEND=tensorflow TF_KERAS=1
  - KERAS_BACKEND=tensorflow TF_KERAS=1 TF_EAGER=1
  - KERAS_BACKEND=tensorflow TF_KERAS=1 TF_2=1
  - KERAS_BACKEND=theano THEANO_FLAGS=optimizer=fast_compile
  # - KERAS_BACKEND=cntk PYTHONWARNINGS=ignore
install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - export LD_LIBRARY_PATH=$HOME/miniconda/envs/test-environment/lib/:$LD_LIBRARY_PATH
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - if [[ $TF_2 == "1" ]]; then pip install tensorflow==2.0.0-beta0; fi
  - if [[ $KERAS_BACKEND == "theano" ]]; then pip install theano && conda install mkl mkl-service; fi
  - if [[ $KERAS_BACKEND == "cntk" ]]; then
      set -e &&
      pip install cntk &&
      mkdir -p ~/mpi &&
      pushd ~/mpi &&
      wget http://cntk.ai/PythonWheel/ForKeras/depends/openmpi_1.10-3.zip &&
      unzip ./openmpi_1.10-3.zip &&
      sudo dpkg -i openmpi_1.10-3.deb &&
      popd;
    fi
  - pip install coveralls
script:
  - ./test.sh
after_success:
  coveralls
